name: Deploy SHIELD dbt to Prod and Test

on:
  schedule:
    - cron: '*/50 * * * *'

jobs:
  # deploy-test:
  #   runs-on: ubuntu-latest
  #   env:
  #     DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
  #     DBT_SERVER_TEST: ${{ secrets.DBT_SERVER_TEST }}
  #     DBT_PORT_TEST: ${{ secrets.DBT_PORT_TEST }}
  #     DBT_USER_TEST: ${{ secrets.DBT_USER_TEST }}
  #     DBT_PASSWORD_TEST: ${{ secrets.DBT_PASSWORD_TEST }}
  #     DBT_DATABASE_TEST: ${{ secrets.DBT_DATABASE_TEST }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         ref: dev

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install dbt-postgres
  #         dbt deps --profiles-dir ./profiles/ --target test
  #     - name: Run dbt seeds for test
  #       run: |
  #         dbt seed --profiles-dir ./profiles/ --target test --full-refresh
  #     - name: Run dbt models for test
  #       run: |
  #         dbt run --profiles-dir ./profiles/ --target test
    

  deploy-prod:
    runs-on: ubuntu-latest
    env:
      DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
      DBT_SERVER_PROD: ${{ secrets.DBT_SERVER_PROD }}
      DBT_PORT_PROD: ${{ secrets.DBT_PORT_PROD }}
      DBT_USER_PROD: ${{ secrets.DBT_USER_PROD }}
      DBT_PASSWORD_PROD: ${{ secrets.DBT_PASSWORD_PROD }}
      DBT_DATABASE_PROD: ${{ secrets.DBT_DATABASE_PROD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres
          dbt deps --profiles-dir ./profiles/ --target prod
      - name: Run dbt seeds for prod
        run: |
          dbt seed --profiles-dir ./profiles/ --target prod --full-refresh
      - name: Run dbt models for prod
        run: |
          dbt run --profiles-dir ./profiles/ --target prod
